name: Black Ops Productions
favicon: null
layout_spectrum: 0.8800950169097632
typography_spectrum: 0.8547434497158974
title: Black Ops Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fafafa'
    - '#5a5859'
    - '#222222'
    - '#d0d0d0'
  brandStrength: 0.8423111697193235
  lightness: 0.5938065603841096
  saturation: 0.6650835864711553
  rhythmicContrast: 0.9819960491731763
purpose: []
